name: build_outputs_script
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dio: any
  args: any

dev_dependencies:
  pedantic: ^1.9.0
executables:
  build_outputs_script:
